#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Mar  7 22:23:12 2018

@author: navyabattu
"""
#Importing csv, numpy, lda
import csv
import numpy as np
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis


x_axis = []
y_axis = []
# Writing the data into x_axis and y_axis
with open("data.csv") as f:
    csvfile = csv.reader(f, delimiter=',')
    next(csvfile)
    for line in csvfile:
        loan = float(line[0])
        deposit = float(line[1])
        amount = float(line[2])
        interest = float(line[3])
        area = 1 if float(line[4]) > 0 else 0
        x_axis.append([loan, deposit, amount, interest])
        y_axis.append(area)
# Converting the data in x_axis and y_axis into numpy array
np_x = np.array(x_axis)
np_y = np.array(y_axis)
# LDA
model = LinearDiscriminantAnalysis()
model.fit(np_x, np_y)
# Loan issued prediction
loan = 30
deposit = 60
interest = 4
amount = 0.3
print("Loan requirements will be met only when : "
      "loan [%f] should be in the particular range, "
      "deposit [%f] must be assigned as per the loan, "
      "interest [%f] in percentage is calculated,"
      " and  amount [%f] in certain limit" % (loan, deposit, amount, interest))
if model.predict([[loan, deposit, amount, interest]])[0]:
    print("Loan may be issued.")
else:
    print("Loan may not be issued.")
# Load not issued prediction
loan = 5
deposit = 25
interest = 0.6
amount = 5.9
print("Loan requirements will be not met when: "
      "loan [%f] should be in the particular range, "
      "deposit [%f] must be assigned as per the loan, "
      "interest [%f] in percentage is calculated,"
      " and  amount [%f] in certain limit" % (loan, deposit, amount, interest))
if model.predict([[loan, deposit, amount, interest]])[0]:
    print("Loan may be issued.")
else:
    print("Loan may not be issued.")